name: Compiling the proofs

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: coq-community/docker-coq-action@v1
      with:
        coq_version: "8.10"
        script: |
          startGroup "Build project"
            make -j2
          endGroup
