name: Release Artifacts

on:
  push:
    branches: [ main ] # for now, build always
    # tags:
    #   - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  # This job is almost like ci-demo.yml, but optimizes the website to run locally
  build-website:
    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/demo-sources/Gemfile

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
        bundler-cache: true

    - name: Install JavaScript Dependencies
      working-directory: demo-sources
      run: npm install

    - name: Run Webpack to bundle JS files (Monaco and compiler)
      working-directory: demo-sources
      run: webpack

    - name: Build page
      working-directory: demo-sources
      run: bundle exec jekyll build
      
    - name: Zip built website
      working-directory: demo-sources
      run: mv _site website; zip -r website.zip website

    - name: Save zip file
      uses: actions/upload-artifact@v1
      with:
        name: website
        path: demo-sources/website.zip
        
  compile-proofs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: coq-community/docker-coq-action@v1
      with:
        coq_version: "8.10"
        before_script: |
          startGroup "Workaround permission issue"
          sudo chown -R coq:coq ./coq  # <--
          endGroup
        script: |
          startGroup "Build project"
          cd coq; make -j2
          endGroup

    - name: Revert permissions
      # to avoid a warning at cleanup time
      if: ${{ always() }}
      run: sudo chown -R 1001:116 coq
    
    - name: Zip compiled proofs
      run: zip -r compiled-proofs.zip coq

    - name: Save zip file
      uses: actions/upload-artifact@v1
      with:
        name: compiled-proofs
        path: compiled-proofs.zip
